Octaforce/algorithm-study

Baekjoon/연속합 2/연속합 2_박수빈

#3
한 원소를 제거할 수 있다는 것에서 어떻게 해야할지 아이디어가 떠오르지 않았다.
역방향으로 DP를 한 번 더하고, 마지막에 하나의 원소를 제거하며 비교해보는 메서드 추가
다른 방법이 있다면 궁금합니다 !!

solved 연속합 2 - 252ms 25540KB

---

CodeTree/2개의 사탕/2개의 사탕_이정명.java

#2 
시간 안에 못풀었습니다
따로 또 같이 움직인다는 점만 생각하다. 순서에 따른 에러를 체크 못했습니다.
- BFS
X

unsoved 2개의 사탕

---

Baekjoon/LCS 2/LCS 2_김예지.js

#1 
사실 1년전에 푼 문제인데 다시 보려니까 못하겠더라구요 어려웠습니다.
DP 사용했습니다. 
예전에 python으로 푼거 javascript로 다시 해보면서 js에서 문자열 뒤집어서 출력하는 방법같은 소소한거 새로 공부했습니다.
없습니다

solved LCS 2 - 208ms 24776kb

---

Baekjoon/빗물/빗물_김예지.js

#4 
처음에 아이디어가 생각이 안나서 조금 걸렸지만, 아이디어만 있다면 금방 푸는 문제였습니다.
딱히 특정 알고리즘으로 푼 건 아니고
각 요소마다 자신을 기준으로 왼쪽에서 가장 큰것, 오른쪽에서 가장 큰 것을 각각 구한 후, 그 둘의 최솟값 - 자신 높이를 해주면 구할 수 있는 아이디어만 있으면 풀 수 있는 문제였습니다.
가끔 코테보다 보면 이런 문제가 몸풀기용으로 나오는 것 같은데 생각하는 연습을 할 수 있어서 저는 좋았습니다
특정 알고리즘을 사용해서 풀 수가 있는지가 궁금합니다.

solved 빗물 - 92ms 11272kb

---

Baekjoon/연속합-2/연속합-2_최근영.py

#3 
- 처음 접근을 누적 합을 이용해서 접근했습니다.
- 누적 합을 구하면서 제일 낮은 수를 제거하고 모두를 더하면 문제에서 요구하는 최적의 값이 나올거라 생각했지만 앞에서 작은수를 쳐내는 것으로 높은 수가 나오는 경우도 존재해서 접근 방식을 다르게 바꿨습니다.
- 2번의 DP를 활용
- 메모리 자체가 512MB로 널널한 편이라 리스트 2개를 활용하여 모든 값을 더한 식과 한 수를 제거한 점화식을 활용하여 풀이함
- 없습니다.
- [ ✔] Convention(commit, pr 제목)이 올바른가요?
- [ ✔] 괄호 내 안내문은 삭제하셨나요?
- [ ✔] 본인의 체감 난도 Label을 등록했나요?
- [✔] 제출자 확인 사항을 모두 확인하셨나요?

solved 연속합 2 - 128ms 44996kb

---

Baekjoon/LCS 2/LCS 2_박수빈

#1
처음에 dp 배열을 String으로 했다가 메모리 초과가 나서 당황했었다.
LCS의 길이를 구하고, 이를 활용하여 다시 문자열을 구하는 과정이 어려웠다.
dp를 int[][] 로 두고 백트래킹해서 문자열 구하기
딱히 없습니다.

solved LCS 2 - 156ms 18992KB

---

Baekjoon/빗물/빗물_박세건.java

#4 
- 스택은 빠르게 생각했지만, 스택을 어떻게 이용할 것인지를 고민 했던 문제
- 스택 자료구조를 사용
- 현재의 깊이는 어떻게 측정되고 길이(가로)는 어떻게 구할 수 있는지
없습니다.

solved 빗물 - 112ms 14292kb

---

Baekjoon/연속합 2/연속합 2_박세건.java

#3 
- 처음 알고리즘 선택을 잘못해서 시간을 많이 사용했습니다.
- 문제를 보고 어떤 알고리즘을 선택해야할지를 빠르게 파악하는 것을 길러야겠습니다.
- 문제를 보고 누적합을 떠올렸으나 N^2 ~ N^3 의 시간 복잡도로 시간초과가 발생할 가능성 확인
- dp를 사용해서 제거된 경우와 제거되지 않은 경우를 나눠서 점화식 구성
- 없습니다.

solved 연속합 2 - 288ms 27704kb

---

Baekjoon/캠프준비/캠프준비_이정명.java

#5 
생각보다는 어려웠습니다. big값과 small값을 쓰지 않으려고 부단히 노력했으나 생각보다 머릿속에서 꼬여서 잘 안되고, 알고리즘이 오히려 복잡하게 풀려서 고생했습니다.
- 기존에 풀려던 방식 : 문제의 난이도 정렬 -> [마지막 값 - 첫 값 < X] 경우, 연산 pass를 통한 최적화
- 제약조건 포함 조합

solved 캠프준비 - 72ms 11776kb

---

Baekjoon/빗물/빗물_이정명.java

#4 
비슷한 문제를 풀었다보니 아이디어 쪽은 비교적 쉽게 풀었습니다만 오래간만에 푸니까 코딩하는 손이랑 뇌가 조금씩 굳었습니다.
- 분할정복?
- 최고점 기준으로 좌우측으로 나누어서 해결
- PriorityQueue
- 가장 큰 숫자부터 진행해서 작은 숫자에서의 중복 연산을 막음
- 없습니다. 다른 방식이 있다면 궁금합니다.

solved 빗물 - 196ms 18556kb

---

Baekjoon/LCS 2/LCS 2_박세건.java

#1 
- LCS의 길이를 구하는 것은 많이 접해보았지만 문자열을 구하는 접근법이 쉽지 않았다
- 백트래킹을 사용해서 현재의 dp가 어떤 dp로 부터 이어지게 되었는지가 중요했다
없습니다.

solved LCS 2 - 200ms 47656kb

---

Baekjoon/가장 큰 정사각형/가장 큰 정사각형_박세건.java

#25
- 다이나믹을 떠올리기는 간단했지만, 반례들을 해결하는데 오래걸렸던 문제
- DP를 통해 i-1,j-1 번째의 결과를 참고
- 이를 기반으로 가능한 경우를 저장
- 없습니다.

solved 가장 큰 정사각형 - 848ms 27836kb

---

Baekjoon/레이저 통신/레이저 통신_박세건.java

#24 
- 방향성을 생각하지 못해서 시간을 사용했던 문제
- 일반적인 BFS로 탐색하며 꺽이는 부분을 체크
- 이미 방문했던 지점일 경우에는 최적의 경로만 이동할  수 있도록 방향으로 visited 처리
- 없습니다

solved 레이저 통신 - 176ms 20752kb

---

Baekjoon/뱀/뱀_박세건.java

#34 
- 뱀의 꼬리의 이동을 어떻게 처리할지 고민되었음
- 뱀의 움직임은 DFS를 사용해서 머리의 다음 이동을 파악
- 뱀의 몸의 좌표를 관리하기 위해서 꼬리의 다음 이동경로를 파악해야 했음
- 처음에는 4방탐색을 추가해서 찾으려고했지만 반례가 발생, 몸이 바로 겹쳐있을 경우 : ㄹ 모양으로, 때문에 배열로 다음 좌표를 관리
- 없습니다.

solved 뱀 - 120ms 15600kb

---

Programmers/가장 많이 받은 선물/가장 많이 받은 선물_박세건.java

#23
- 문자열과 맵 구조의 내장 함수에 대해 학습할 수 있었으므
- Hash 구조를 사용해서, 문자열을 키로 갖는 Map을 생성하여 정보를 저장하여 해결
- 없습니다.
- 

solved 가장 많이 받은 선물 26.60ms 112mb

---

Baekjoon/영역구하기/영역구하기_이정명.java
Baekjoon/영역구하기/영역구하기_이정명.py

#38
시간복잡도는 고려없이 풀었고, 메모리 줄이기 위해서 boolean 2차원 배열으로 맵처리+방문처리 했습니다.
- bfs, 방문지도, 탐색
- X

solved 영역구하기 - 40ms 33432kb

---

Baekjoon/좋다/좋다_김예지.py

#32 
처음에 살짝 헤맨거 빼고는 쉬웠습니다
투포인터를 사용했습니다
- 숫자들을 정렬하고,
- 각 숫자에 대해서 투포인터를 이용해서 자신을 만들 수 있는지 확인하는 방식
이분탐색을 써보고는 싶었는데 실패했습니다ㅠ
이분 탐색으로 푸신 분이 있다면 참고하고 싶네요

solved 좋다 - 1408ms 32412kb

---

Baekjoon/뱀/뱀_김예지.py

#34 
쉬웠습니다
구현 + 큐
- 뱀의 위치를 큐를 이용해서 조절했습니다
한번에 통과해서 딱히 건들지는 않았지만 방향 전환 위치 조절하는거나, 뱀 길이가 길어지면 시간이 엄청 들어 갈거같은데
다른 분들 방법도 궁금하네요

solved 뱀 - 120ms 114292kb

---

Baekjoon/뱀/뱀_이정명.java
Baekjoon/뱀/뱀_이정명.py

#34 
시뮬레이션 문제인데, 어떻게 관리할지 조금 고민한 문제. 결국은 자신(뱀)과 부딛히는 문제 처리를 위해 2차원 배열map을 구성하여 풀이 진행. 문제를 대충 읽어서 dir이 2방향이라는 것을 못보고 풀었음
- 시뮬레이션
- deque (정확히는 deque 형식을 list로 처리 - 파이썬은 deque를 별도 라이브러리 추가를 해야하는데 추가하고 싶지 않아서)
- 게임오버를 시간 음수값 처리로 진행 (시간이 음수라면 게임오버)
- 시간을 더 줄일 수 있는 방법이 있을까요?

solved 뱀 - 36ms 32412kb

---

Baekjoon/케빈-베이컨의-6단계-법칙/케빈 베이컨의 6단계 법칙_박수빈

#27
- 보자마자 그래프탐색문제 같아서 선정했는데 케빈 베이컨 수 값을 갱신하는 위치를 잘못하고 초기값 설정을 잘못해서 생각보다 오래 헤맸다 
- bfs
- 다른 방법이 있으면 궁금합니다

solved 케빈 베이컨의 6단계 법칙 - 128ms 14936KB

---

Baekjoon/트리-순회/트리 순회_박수빈

#26 
- 트리 개념적인 문제라 난이도는 높지 않은데, 풀 때마다 헤매는 문제
- 트리의 개념
딱히 없습니다.

solved 트리 순회 - 104ms 14220KB

---

Baekjoon/영역 구하기/영역 구하기_박수빈

#38
- 파이썬으로 풀었던 문제를 자바로 그대로 푼 느낌
- bfs
- 딱히 없습니다

solved 영역 구하기_박수빈 136ms 15960KB

---

Baekjoon/사다리/사다리_이정명.java

#29 
- 답을 염탐하고 풀이를 진행했습니다. 정확한 풀이 방법은 길이를 오차 안쪽으로 들어올 때까지 이분 탐색으로 풀었습니다. 답을 본 이유는 설마 연산의 무한 반복이겠어? 했는데, 설마가 진짜였던 경우입니다. 아이디어 자체는 떠올리기 쉬운 편이었는데, 이렇게 풀리겠어 하는 것을 도전하지 않고 답부터 본 점은 반성하는 점입니다. while문 사용하는 것으로 확인한 후에는 의도한 대로 풀 수 있었습니다.
- 이분 탐색
- 수학 (피타고라스 정의, 도형 닮음 정리)

solved 사다리 - 72ms 11892kb

---

Baekjoon/특정한 최단 경로/특정한 최단 경로_최근영.py

#28 
- 기본적인 다익스트라 개념의 문제로 알고 가져왔었는데 막상 접근해보니 다익스트라 + @ 개념이 적용됐던 것 같습니다.
- 특정 노드 두구간을 지나야 했기 때문에 1번 시작노드에서 다익스트라 한 결과값, v1 노드 결과값, v2 노드 결과값을 가져와 계산을 진행해야 했습니다.
- 다익스트라에 살짝 응용되기만 해도 접근이 어려웠기 때문에 좀 더 응용에 대해서 고민해봐야 할 것 같습니다.
- 다익스트라 알고리즘, 최단거리 이론
많이 어려웠을 것 같은데 시간이 어느정도 소비되셨는지 궁금합니다.
- [✔] 제출자 확인 사항을 모두 확인하셨나요?

solved 특정한 최단 경로 - 508ms 70264kb

---

Programmers/산 모양 타일링/산 모양 타일링_이정명.java

#21 
생각보다는 쉽게 풀 수 있었습니다. 코드가 어렵다기 보다는 아이디어 생각하기가 어려웠던 문제였습니다.
- DP

solved 산 모양 타일링 - 22.00ms 85.8MB

---

Baekjoon/좋다/좋다_이정명.py

#32 
- 조건 찾기가 힘들었고, 코드는 짧았습니다.
- 자기 자신에 대한 처리, 중복값 처리, 음수 처리 등이 걸림돌 이었습니다.
- 음수처리가 없었다면 정렬을 통해서 빠르게 처리할 수 있었겠지만, 음수가 있어 그렇게 처리하지 못했습니다.
- X

solved 좋다 - 884ms 32412kb

---

Baekjoon/어드벤처 게임/어드벤처 게임_이정명.java

#33 
- 문제 자체는 어렵지 않았는데, 조건이 부족해서 혼자 이런저런 조건을 추가해서 생각해가며 풀었습니다.
- 부족하다고 생각했던 조건
- 음수일 경우 방문을 못하는 것이 맞는가?
- 중복 방문이 가능한가?
- 최대 몇 번의 케이스가 주어지는 것인가? 등
- bfs로 풀려다가 메모리 문제로 dfs로 변경했지만 메모리 문제 또 발생. 4건의 메모리 초과. 문제는 깊이 우선 탐색에서 class를 사용해서, 메모리가 너무 커졌던 것이 문제. 변수를 통해서 값을 내리는 것으로 처리함.
- 실패조건으로 순환문제와 보유자금이 음수인 경우가 있다고 생각함 (조건은 없음)
- class를 사용하는 것이 아니라 변수를 사용해서 그래프를 구성했으면, 시간+메모리에 효율적이었을 것 (최대 방의 개수가 주어진 것 같으니까)
- 그래프 탐색
- DFS, BFS
- 제출되고 공개된 사람들을 봤을 때, 300ms 대에 끊는 사람들이 많았기에, 다른 사람의 코드를 보는 것도 좋을 것 같습니다. 아마 배열로 푼 경우인 것으로 판단했는데, 같이 보면 좋을 것 같습니다.

solved 어드벤처 게임 - 884ms 51492mb

---

Programmers/가장 많이 받은 선물/가장 많이 받은 선물_이정명.java

#23 
- 문자열 관련이라 파이썬으로 풀까 했다가 자바로 푼 문제입니다.
- BFS
- 시뮬레이션
X

solved 가장 많이 받은 선물 27.69ms 87.9mb

---

Baekjoon/암호 만들기/암호 만들기_박세건.java

#61
- 시간복잡도를 어떻게 구해야하는지 고민되었음
- DFS를 통해서 완전탐색 진행
- 시간복잡도에 대한 계산이 궁금합니다.
- 

암호만들기 - 108ms 14224kb

---

Baekjoon/DSLR/DSLR_이정명.java

#69 
로직은 안어려운데, 메모리랑 시간관리가 조금 걸렸습니다.
방문처리용 배열로 방문처리 (0~9999) 및 지금까지 거쳐온 경로를 비트마스크(4진수) 처리를 통해 처리했는데, 문자열 처리에서 시간이 많이 걸린 것 같습니다.
- 비트마스크
- BFS
- 그래프탐색
- X

solved DSLR - 2708ms 299284kb

---

Baekjoon/암호 만들기/암호 만들기_이정명.java

#61
- 조건 걸린 조합을 이용한 문제.
- 조합
- 백트래킹
- 최저 시간으로 푼 사람이랑 풀이 방식의 디테일이 많이 달라서, 어떤 점이 차이가 크게 나게 되었는지를 고민하는 중입니다.

solved 암호 만들기 - 84ms 11544kb

---

Baekjoon/호텔/호텔_이정명.java

#64 
쉬웠습니다. 처음에 딱 맞게 풀이되는 것이 아니라 넘어가는 부분도 체크해야 했기 때문에 아이디어를 잘못 생각해서, BFS처럼 풀려고 아이디어를 생각했습니다. 최소 소비자 + 도시 별 소비자수 최고값(최대 100)을 더해서 검사하는 형태로 만들어서 DP로 바꿔서 풀 수 있었습니다.
DP의 과정은
1. 최소 수집 소비자 + 도시 별 소비자수 최고값(최대 100) 지도를 생성
2. 1명부터 가능한 모든 경우의 수를 검사 (각 소비자수 별, 최솟값을 기준으로 업데이트 진행)
3. 최소 수집 소비자에 도달한 이후부터는 result를 최솟값으로 업데이트
- DP
5. 제출자의 풀이코드의 좋은 점 혹은 개선사항을 남겨주세요.

solved 호텔 - 72ms	11624kb

---

Baekjoon/암호 만들기/암호 만들기_김예지.js

#61 
어려울줄 알고 골랐는데 그냥 백트래킹하니까 쉽게 풀렸습니다...
네이버 3번이 조합이었던거 같은데 못풀어서 비슷한 문제를 추천받았던 건데 그거보단 쉬웠던거같아요
백트래킹으로 풀었습니다.
- 사전순으로 출력할 것을 고려해서 sort 해주고
- 백트래킹으로 하나씩 넣어서 조건에 맞으면 출력해줬습니다.
백준에서 같은 node.js로 푼 사람들은 시간이나 메모리가 비슷한걸로 봐선 다들 비슷하게 푼 것 같습니다.
다른 어려운 조합문제가 있다면 추천해주세요

solved 암호 만들기 - 160ms 10980kb

---

Baekjoon/DSLR/DSLR_김예지.py

#69 
로직은 쉬운데 시간을 어떻게 단축할지 모르겠습니다...
- 처음에 최단방법이 아니라 무지성 dfs했다가...
- 최단 방법이니 bfs로 바꿨습니다
- python 기준 같은 코드여도 sys.stdin.readline으로하고 pypy3로 해야 시간이 맞습니다..
시간을 어떻게 더 줄일 수 있을지 궁금합니다..

solved DSLR - 4872ms 215436kb

---

Baekjoon/로봇 청소기/로봇 청소기_김예지.py

#67 
방향 처리랑 문제 이해가 좀 어려웠고 구현 난이도는 보통이었습니다
- 문제 조건 놓치지말고 하기
- 반시계방향으로 방향을 틀어야하고, 주어진 방향 번호가 있어서 이걸 처리하는게 조금 헷갈렸습니다.
```python
dire = [[-1, 0], [0, 1], [1, 0], [0, -1]]  # dire[0] = 위
for i in range(4):
new_d = (d - i + 3) % 4 
```
없습니다

solved 로봇 청소기 - 36ms 32412kb

---

Baekjoon/호텔/호텔_김예지.py

#68 
배낭알고리즘... 원래도 못해서 어려웠습니다... 
배낭 알고리즘 dp......
어려워서 하다가 검색찬스 써서 했습니다... 
dp배열의 길이를 어떻게 둘까 했는데, 딱 C인게 아니라 C를 좀 넘어도 최소값이 나올 수 있기때문에 그걸 어디까지 둬야하나를 고민했습니다. 하나의 비용이 최대값이 100이라 그걸 이용해서 했습니다
없습니다

solved 호텔 - 100ms 110736kb

---

Baekjoon/괄호의 값/괄호의 값_최근영.py

#78 
- 생각이 안나서 조건분기 처리를 많이 했습니다...
- 많은 조건 처리 및 예외
- 다른 분들 풀이가 궁금합니다

solved 괄호의 값 - 36ms 32412kb

---

Baekjoon/가장 큰 정사각형/가장 큰 정사각형_최근영.py
Baekjoon/수 묶기/수 묶기_최근영.py
Baekjoon/호텔/호텔_최근영.py

#88
- 접근하는 방법에 대해서 고민을 많이했던 문제였습니다.
- 기존에 비슷한 풀이의 문제를 접해봐서 조금 시간이 덜 걸렸던 것 같습니다.
- 정렬, 리스트 분할
X

solved 수 묶기 - 32ms 32412kb

---

Baekjoon/뱀과 사다리 게임/뱀과 사다리 게임_최근영.py
Baekjoon/피보나치 수 3/피보나치 수 3_최근영.py

#79 
- BFS 를 통한 1번 부터 시작해서 주사위수 1~6 사이에 갈 수 있는 거리를 모두 체크해주는 방식으로 풀었습니다.
- 주사위 수 내에서 사다리, 뱀 존재 여부를 딕셔너리를 통해 시간복잡도를 조금이라도 줄이는 방식 사용
- 딕셔너리, BFS
X

solved 뱀과 사다리 게임 - 68ms 34944kb

---

Baekjoon/피보나치 수 3/피보나치 수 3_최근영.py

#85 
- 기존의 피보나치 접근법 외에는 생각이 나질 않아서 메모리 줄일겸 deque 로 접근 시도해봤지만 n 의 값이 너무커서 방법을 모르겠습니다.
X 
X

unsolved 피보나치수 3

---

Baekjoon/피보나치 비스무리한 수열/피보나치 비스무리한 수열_최근영.py

#82 
- 오랜만에 피보나치 개념을 다시 생각해볼 수 있었습니다.
- DP
X

solved 피보나치 비스무리한 수열 - 36ms 32412kb

---

Baekjoon/괄호의 값/괄호의 값_박세건.java

#78
- 문제를 보고 스택구조로 해결할 수 있다는 것을 바로 알 수 있었지만 내부의 값을 구해주는 과정을 재귀문으로 작성하려다가 구현하지 못했고 해당 로직을 구현하는 부분이 쉽지 않아서 시간을 많이 사용했습니다.
- 스택구조를 사용해서 깊이에 따른 값들을 저장하여 관리해야하는 점이 핵심이라고 생각
- 해당 값들을 저장해서 관리하기 위해서 괄호와 값(Integer)를 같이 보관할 수 있는 Stack을 만들어줌
- 재귀로 해결하신 분 있으면 궁금합니다.

solved 괄호의 값 - 108ms 14308kb

---

Baekjoon/탑 보기/탑 보기_박세건.java

#80 
- 문제를 보고 빠르게 스택 구조를 생각할 수 있었음
- 스택을 사용해서 현재 내가 탐색하고 있는 높이보다 작은 값들을 스택에서 없애면서 진행
- 없습니다.
- 

solved 탑 보기 - 564ms 38156kb

---

Baekjoon/피보나치 비스무리한 수열/피보나치 비스무리한 수열_박세건.java

#82 
- 쉽게 봤다가 혼났던 문제
- 
- DP 알고리즘의 특징상 결과값이 Integer 값을 넘길 수 있다는 점
- 입력이 3보다 작을 수 있다는 점
- 없습니다.
- 

solved 피보나치 비스무리한 수열 - 108ms 14304kb

---

Baekjoon/피보나치 수 3/피보나치 수 3_박세건.java

#85 
- N이 무수히 크다는 것을 확인해서 일정한 규칙이 존재할 것이라고 생각했지만, 찾지 못했음
- 시간을 줄이기 위해서 반복되는 규칙이 존재하는 줄 알았지만, 그렇지 않았음
- 규칙성이 존재하는지 궁금합니다.

unsolved 피보나치 수 3

---

Baekjoon/수 묶기_박세건.java

#88 
- 반례를 찾지 못해서 해결하지 못함
- 예외 상황이 발생할 수 있는 경우를 제거하는 방식으로 진행
- 어떤 예외 상황을 막아줘야하는지 궁금합니다.

unsolved 수 묶기

---

Baekjoon/괄호의 값/괄호의 값_이정명.python

#78 
- 쉬웠습니다. 문자열 관련이라 자바로 했다면 문자열 부분에서 조금 시간이 걸렸을 것 같은데, 파이썬이라 크게 생각안하고 처리했습니다.
- 스택에 괄호에 해당하는 값(-2, -3)을 넣고, 연산 과정을 순서대로 처리했습니다. (초기값은 어디에도 나오지 않는 괄호랑 같은 형식(음수)의 값인 -1로 설정)
- 기본적으로는 스택을 쌓아가다가, ```)```혹은 ```]```을 만나면 pop으로 스택을 비워줍니다.
- 그 과정 중, 예상치 못한 값(값에 맞는 여는 괄호 외의 음수 값)이 나올 경우, 0을 반환하는 함수를 만듭니다.
- 만약 연산이 오류없이 완료된다면, 사용하지 않은 여는 괄호(-2, -3)에 해당하는 값이 남아있는지 확인합니다.
- 이 과정을 모두 통과한다면, 스택에 들어있는 모든 값들을 덧셈 연산을 통해서 합한 후, 초기값인 -1을 +1로 없애줍니다.
- 스택
- X

solved 괄호의 값 - 40ms 32412kb

---

Baekjoon/피보나치 비스무리한 수열/피보나치 비스무리한 수열.py

#82 
- 사실상 피보나치 수열 문제, 조금의 개선사항은 초기값을 넣어야하는 방식 대신 반복문 안에서 모든 것을 다 처리하고자 했습니다. 파이썬으로 풀어, 조금 더 쉽게 접근 가능했습니다. (리스트에도 길이 추가 가능)
- 피보나치 수열
X

solved 피보나치 비스무리한 수열 - 44ms 32412kb

---

Baekjoon/괄호의 값/괄호의 값_김예지.py

#78 
점수처리하는 부분을 생각하는게 어려웠습니다.. 한시간 고민하다가 gpt찬스 썼습니다..
- stack...? 
다른 방법이 있을까요
저는 특정 알고리즘을 사용해서 푼 느낌이 아니라서..

solved 괄호의 값 - 44ms 32412kb

---

Baekjoon/피보나치 수 3/피보나치 수 3_이정명.py

#85 
- 어려웠다기보다는 피보나치 수열이 피사노 주기라는 이름으로 주기성을 가진다는 사전 지식이 없으면 풀 수 없는 문제(시간초과로) 였습니다.
- 피보나치 수열
- 비슷하게 푼 것 같은데 시간이 차이가 많이 나는 경우가 발생했습니다. 어떤 이유인지 파고들 필요가 있습니다.

solved 피보나치 수 3 - 228ms 32412kb

---

Baekjoon/피보나치 수 3/피보나치 수 3_김예지.py

#85 
옛날에 풀다가 실패한 문제라... 크게 어렵지 않을 줄 알았는데 너무 어려웠습니다... 수학이었어요.... ~죄송합니다~
행렬곱과 분할정복을 이용했습니다.
https://memezzi.notion.site/3-1cd77521bf908051a668dd151f5cbf49?pvs=4
다른 방법이 있다면,... 피사노 주기라는 것도 있던데 그걸 알아서 푸신분이 있나요 전 완전 처음들어봤어요

solved 피보나치 수 3 - 32ms 32412kb

---

Baekjoon/피보나치 수 3/피보나치 수 3_박수빈.java

#85 
- n의 크기가 너무 커서 헤맸다
- 피사노 주기
- 다른 방식이 있다면 궁금합니다.

solved 피보나치 수 3 - 124ms 25952kb

---

Baekjoon/DSLR/DSLR_김예지.py
Baekjoon/뱀과 사다리 게임/뱀과 사다리 게임_김예지.py

#79 
못풀었습니다ㅜㅜ 메모리 초과때문에..
dfs로 했는데 방문처리를 해야할까요,,, 어디서 메모리 초과인지 감이 안와요
푼 분들 로직이 궁금합니다

unsolved 뱀과 사다리 게임 - 김예지

---

Baekjoon/보석 도둑/보석 도둑_박세건.java

#110 
- 시간이 없어서 풀지 못했음
- 보석과 가방을 정렬한다면 그리디하게 풀어낼 수 있다고 생각했음 
- 해결방식이 궁금합니다.

unsolved 보석 도둑

---

Baekjoon/파일 합치기 3/파일 합치기 3_박세건.java

#111 
- 최적을 생각보다 빠르게 찾을 수 있었다
- 합쳐지는 값이 작을 값들이여야함
- pq 사용
- 없습니다.

solved 파일 합치기 3 - 2604ms 278356kb

---

Baekjoon/타임머신/타임머신_박세건.java

#108 
- 많이 사용하지 않았던 벨만 포드 알고리즘에 대해 알아갈 수 있었음
- 벨만포드 알고리즘을 사용
- 플로이드 워셜이나 DP 개념을 이용했다면 해결할 수 있었을 듯
- 없습니다.

solved 타임머신 - 280ms 19476kb

---

Baekjoon/ABCDE/ABCDE_박세건.java

#109 
- 백트래킹을 이용하여 쉽게 해결할 수 있었음
- 백트래킹 다시 개념익히기에 좋음
- 백트래킹을 통한 DFS와 방문처리를 이용
- 없습니다.

solved ABCDE - 260ms 17628kb

---

Baekjoon/파일 합치기 3/파일 합치기 3_박수빈.java

#111 
- 로직 생각하는 거에 시간이 좀 들었습니다
- 큰 파일은 최소한으로 더한다 + 우선순위 큐
- 다른 방식이 있다면 궁금합니다.

solved 파일 합치기 3 - 2908ms 324660kb

---

Baekjoon/ABCDE/ABCDE_김예지.py

#109 
백트래킹이 오랜만이라 좀 어려웠습니다. 문제 자체는 무난한 백트래킹 문제인거 같습니다.
백트래킹
없습니다

solved ABCDE - 488ms 112152kb

---

Baekjoon/파일 합치기 3/파일 합치기 3_최근영.py

#111
- 접근 하는 방식이 생각이 아예 안나서 풀지를 못했습니다.
- 뭔가 DP 느낌이 나면서도 아닌거 같아서 다른 풀이가 궁금합니다.
x
X

unsolved 파일 합치기 3

---

Baekjoon/ABCDE/ABCDE_이정명.java

#109 
쉬웠는데, 문제 이해를 잘못했습니다. 5명만 연속되면 된다는 명시적인 말이 없어서, 전체가 다 연결된 그래프 탐색을 하고 있었습니다.
- 친구 관계를 저장(배열X 그래프)
- 0부터 N까지 순서대로 한 사람씩을 기준으로 순회 시작
- 5개 이상 연결되는 연결이 있는지 확인하기 위해 BFS 순회 (순회하는 동안 방문체크를 통해 반복 방문 제외)
- 그래프 탐색
- DFS (OX 문제이기에 시간 최적화를 위해 BFS 사용 안함)

solved ABCDE - 176ms 13240kb

---

Baekjoon/타임머신/타임머신_이정명.java

#108 
- 오래간만에 벨만 포드를 작성해서 작성 방법에 조금의 혼란이 있었습니다.
- 벨만 포드
- 그래프
- X

solved 타임머신 - 240ms 17132kb

---

Baekjoon/타임머신/타임머신_김예지.py

#108 
벨만포드를 까먹어서 어려웠습니다..
벨만포드 알고리즘
- 음수싸이클을 고려를 못해서 좀 헤맸습니다..
없습니다

solved 타임머신 - 276ms 112028kb

---

Baekjoon/램프/램프_최근영.py
Baekjoon/보석 도둑/보석 도둑_최근영.py

#135 
- 완전 탐색으로 접근을 했는데 풀이법이 아예 떠오르지 않아서 질문 게시판이랑 조금 찾아봄
- 같은 형태의 리스트를 체크한 후 0의 개수가 K 보다 작거나 같고 K 에서 현재 0 의 개수를 뺀 값이 짝수인 경우 그 형태 자체를 저장하는 식으로 접근함
- 마지막에 그 형태가 가장 많은 부분을 출력하면된다.
- 브루트 포스
x

solved 램프 - 44ms 32412kb

---

Programmers/가사 검색/가사 검색_이정명.py

#132 
- 풀이 방식에 따라서 난이도가 달라졌을 것 같습니다.
- 이분 탐색
- 양측으로 나누어 탐색했습니다.
- 문자열을 뒤집는 방법을 선택해서 정렬하고 정렬된 문자열을 기준으로 기준에 들어오는 첫 값과 끝 값을 만들어 사이 값들의 개수를 구해줬습니다.
- 트라이(TRIE)
- 문자열을 저장하고 효율적으로 탐색하기 위한 트리 형태의 자료구조
- 처음에 생각한 방식이었습니다. 하지만, 글자 수에 따라 별도의 처리가 필요할 것으로 생각되어 이분 탐색으로 진행했습니다.
- 이분탐색
- 트라이
- X

solved 가사 검색 - 245ms 25mb

---

Baekjoon/신입 사원/신입 사원_박수빈.java

#138 
- 크게 어렵진 않았는데 입력 들어온 순서를 기억하며 시험 점수와 면접 점수를 저장하는 방법을 좀 고민했습니다.
- 그리디
- 다른 방시기 있다면 궁금합니다.

solved 신입 사원 - 836ms 301580kb

---

Baekjoon/텀 프로젝트/텀 프로젝트_이정명.java

#131 
- 쉬운 편이었습니다. 최적화를 먼저 생각하고 풀 수 있게 방향성을 잡아줘서, 그거만 생각하면서 풀었습니다.
- 저는 시간 초과가 한 번이 떴는데, 중복 체크를 한 줄 알았는데 하지 않아서 생겼던 시간초과였습니다.
- DFS
- 방문처리
- 없습니다.

solved 텀 프로젝트 - 1752ms 308912kb

---

Baekjoon/압축/압축_박세건.java

#140 
- 재귀문으로 내부의 값을 확인해서 해결하려 했지만, 반례를 해결하지 못함
- 재귀문으로 ( ) 내부의 값만 뽑아내서 해결
- 없습니다.

unsolved 압축

---

Baekjoon/램프/램프_박세건.java

#141 
- 해결 방법을 찾지 못함
- 완전탐색을 생각했으니 2^50 경우는 시간초과가 발생할 것 같았고 그 밖에는 생각하지 못함
- 해결 방법이 궁금합니다.

unsolved 램프

---

Baekjoon/수식 최대화/수식 최대화_이정명.py

#133 
- CI/CD 테스트용 몸풀기 문제였습니다. (그래서 코드를 막짰습니다.)
- stack
- 순열

solved 수식 최대화 - 0.25ms 9280kb

---

Baekjoon/텀 프로젝트/텀 프로젝트_김예지.py

#131 
어려웠습니다... 분명 1년전에 푼 기록이 있는데 안풀려서 1년전의 저에게 배워서 풀었습니다...ㅠ
DFS인데 방문처리와 사이클 처리가 어려웠습니다.
사이클이 발생하면 시작점의 인덱스를 구해서 팀 인원을 구하는 방식으로 했습니다
없습니다
- [x[ Convention(commit, pr 제목)이 올바른가요?

solved 텀 프로젝트 - 2704ms 50940kb

---

.github/scripts/label-pr.js
Baekjoon/신입 사원/신입 사원_이정명.java

#138 
- 순간적으로 문제가 이해가 안갔었는데, 이해하니 로직은 어렵지 않았습니다.
- ver1에서는 priorityQueue로 정렬해서 해결했습니다. 한 점수(코드에서는 처음 나온 값)를 기준으로 정렬 후, 최솟값 갱신 방식으로 처리했습니다.
- ver2에서는 한 점수(코드에서는 처음 나온 값)를 배열의 위치(중복 없으므로)로 사용해서 정렬없이 최솟값 갱신 방식으로 처리했습니다.
[ver1]
- 정렬
- Priority Queue
[Ver2]
- 배열

solved 신입 사원 - 916ms 298780kb

---

Programmers/가사 검색/가사 검색_박세건.java

#132 
- 문자열 다루는 함수들에 대해 다시 상기시킬 수 있었음
- 가능한 가사를 모두 구하는 것은 시간초과 발생할 것이라 생각
- 가능한 가사의 범위를 구해야한다고 생각하여 처음과 끝을 이분탐색으로 해결
- 없습니다.

solved 가사 검색 - 299ms 94mb

---

Baekjoon/신입 사원/신입 사원_박세건.java

#138 
- 간단한 정렬 문제
- 정렬과 순위를 최솟값을 유지하는게 핵심
- 없습니다.

solved 신입 사원 - 2856ms 314724kb

---

Baekjoon/탑/탑_이정명.java

#152 
- 전에 풀어봤던 문제라서 쉽게 접근했는데, 풀고보니 접근법이 완전히 달랐습니다. (지금이 더 개선된 버전)
- 지금은 스택을 통해 풀이를 진행했고, 지금까지 진행하면서 나보다 큰 것들이 있었는지 검사하는 방식이었는데, 나보다 작은 것들은 비교 대상(stack)에서 제외하면서 검색하는 횟수를 줄였습니다.
- Stack
- 정렬?

solved 탑 - 668ms 114260kb

---

Baekjoon/트리의 지름/트리의 지름_박세건.java

#154 
- 처음에 생각한 방식으로는 메모리 초과가 발생하여 풀이법을 참고해서 해결
- 트리의 지름의 특성에 대한 규칙을 찾아내서 해결하는 방식
- 임의의 점에서 가장 먼 거리는 트리의 지름을 구성하는 노드중 하나 일것
- 없습니다.
- 

solved 트리의 지름 - 204ms 22784kb

---

Baekjoon/탑/탑_박세건.java

#152 
- 스택구조를 떠올리기 적절한 문제였음
- 스택구조를 이용해서 자신보다 높은 탑의 번호를 어떻게 자신의 위치에 출력시키는 것이 중요
- 없음.

solved 탑 - 700ms 99100kb

---

Baekjoon/이중 우선순위 큐/이중 우선순위 큐_박세건.java

#153 
- 우선순위큐를 쉽게 떠올릴 수 있었음
- Map을 사용해서 숫자의 사용횟수를 기록하하여 제거되었는지를 확인
- k를 배열로 관리하면 더 빠른지 궁금

solved 이중 우선순위 큐 - 2976ms 361648kb

---

Baekjoon/앱/앱_박세건.java

#162 
- 배낭 문제는 떠올리기 쉬웠지만, 기준을 잡는 것에서 고민함
- 기본적인 배낭 문제는 크기, 즉 M에 대해서 기준을 잡지만 해당 문제는 M이 10,000,000 으로 시간초과가 발생. 때문에, 입력으로 주어진 c를 기준으로 설정해서 진행
- x

solved 앱 - 132ms 18876kb

---

Baekjoon/합이 0인 네 정수/합이 0인 네 정수_박세건.java

#163 
- 기존의 접근 방법으로는 해결하지 못해 해결 사례를 참고해서 해결함
- 반례들을 참고해서 해결할 수 있었음
- 이분탐색을 통해서 일치하는 원소들을 빠르게 탐색하는 것
- 투포인터 방식을 이용해서 1차원 적인 탐색으로 진행하는 것
- 없습니다.

solved 합이 0인 네 정수 - 4392ms 162908kb

---

Baekjoon/과외맨/과외맨_박세건.java

#164 
- BFS로 접근하려 했지만, 낯개로 진행하면 될줄알고 헤매었던 문제
- BFS를 탐색할때의 낯개가 아닌 블럭 단위로 진행하도록 함 
- 낯개로 풀릴 수 있을 것이라고 생각했는데 안풀린 이유가 궁금

solved 과외맨 - 546ms 82684kb

---

Baekjoon/섬의 개수/섬의 개수_박수빈.java

#167
- 그래프 탐색을 복기하기에 좋았다.
- BFS
- 딱히 없습니다.

solved 섬의 개수 - 152ms 16108kb

---

Baekjoon/앱/앱_박수빈.java

#162
- 시간초과를 해결하는 것에서 시간이 좀 걸렸다
- 냅색, dp
- 딱히 없습니다.

solved 앱 - 124ms 14516kb

---

Baekjoon/과외맨/과외맨_김예지.py

#164 
어려웠습니다........
bfs인데, 시간 초과랑 타일 기준으로 최소경로를 해야해서 그래프 개념을 같이 써서 풀었습니다
좀 더 쉬운 방법이 있을까요...

solved 과외맨 - 484ms 202160kb

---

Baekjoon/섬의 개수/섬의 개수_박세건.java

#165 
- BFS, DFS 알고리즘 복기하기 적절했음
- BFS, DFS 중 어떤 것이 더 빠를지를 고민해봄
- BFS보다 DFS가 빠를 줄 알고 접근함
- 왜 BFS가 더 빨랐을지 궁금합니다.

solved 섬의 개수 - 140ms 15888kb

---

Baekjoon/트리의 지름/트리의 지름(2)_박세건.java

#175 
- 이전에 접했던 트리의 지름에 대한 정의를 통해 빠르게 접근하여 해결
- 하나의 노드에서 가장 먼 노드를 선택하면 트리의 지름을 이루는 두가지 정점 중 하나이다
- 없습니다.

solved 트리의 지름 - 1008ms 104928kb

---

Baekjoon/회의실 배정/회의실 배정_박세건.java

#176 
- 2차원 정렬 및 그리디 알고리즘 복기하기 좋은 문제
- 끝나는 시간을 기준으로 오름차순으로 진행 먼저하고 그다음 시작하는 시간을 기준으로 오름차순으로 정렬을 진행
- 시작하는 시간의 경우 내림차순으로 정렬할때 반례가 발생함 (7,7), (5,7)  순서로 되면 원래는 동시에 사용 가능한데 사용 못하게됨
- 없습니다.

solved 회의실 배정 - 484ms 44324kb

---

Baekjoon/용액 합성하기/용액 합성하기_이정명.java

#174 
- 쉽게 풀었습니다. 조합을 쓸까, 투포인터를 쓸까 하다가 투포인터가 성능이 더 나을 것으로 판단해서, 투포인터를 사용했습니다.
- 어떤 포인터를 움직일지(좌/우)는 두 포인터에 위치한 값의 합이 음수인지 양수인지를 판단해서 진행했습니다. (0일 경우 더 작은 값이 없으므로 그 자리에서 종료)
- 값을 갱신하는 것은 3항 연산자를 활용해서 절댓값을 기준으로 비교해서 갱신했습니다.
- 투포인터

solved 용액 합성하기 - 228ms 27516kb

---

Baekjoon/회의실 배정/회의실 배정_박수빈.java

#181 
2차원 배열 정렬과 그리디를 복기하기 좋았다
- 2차원 배열 정렬, 그리디
- 딱히 없습니다.

solved 회의실 배정 - 464ms 43384kb

---

.github/workflows/Auto-Labeling-PR.yml
Baekjoon/회의실 배정/회의실 배정_이정명.py

#176 
- 어렵지 않았습니다. 그리디를 이용한 문제였고, 가장 빨리 끝나는 것들 중 가능한 것이 있는지 찾는 것이 가장 핵심 로직 이었습니다.
- 파이썬에서 2차원 정렬?을 하는 방식(lambda)
- 그리디

solved 회의실 배정 - 424ms 137612kb

---

Baekjoon/소문난 칠공주/소문난 칠공주_박세건.java

#177 
- 접근법을 찾는것이 오래걸렸음
- dfs방법으로 7개를 선택하는 것은 맞지 않다고 생각하여 조합 개념을 사용해서 7개를 무작위로 선택해서 진행
- 7개를 무작위로 선택하고 문제에서 제시한 4개 이상을 확인했다면 그때 BFS를 돌려서 모든 공주들을 찾아낼 수 있는지를 확인
- 없습니다.

solved 소문난 칠공주 - 720ms 162904kb

---

Baekjoon/용액 합성하기/용액 합성하기_김예지.py

solved 용액 합성하기 - 60ms 44748kb

---

Baekjoon/개똥벌레/개똥벌레_박세건.java

#188 
- 해결법에 접근하기 어려웠음
- 각각의 주어진 위, 아래 정보를 따로 분리해서 저장해서 정렬해서 관리하려고함
- 풀이법이 맞는지 궁금합니다.

unsolved 개똥벌레

---

Baekjoon/벽 부수고 이동하기/벽 부수고 이동하기_박세건.java

#190 
- BFS 복기하기에 좋은 문제
- 방문처리를 문을 부셨을때를 나눠서 관리
- 없습니다.

solved 벽 부수고 이동하기 - 660ms 113724kb

---

Baekjoon/개똥벌레/개똥벌레_이정명.py

- #188 
- 쉬웠습니다. 누적합과 홀짝으로 분리해서 저장하는 것만 정리를 잘 하면 쉬운 문제였습니다.
- 누적합
- 누적합을 더 잘 정리할 수 있는 방법이 있을까요?

solved 개똥벌래 - 508ms 72296kb

---

Baekjoon/개똥벌레/개똥벌레_김예지.py

#188 
처음에 감이 안와서 컨셉을 찾아보고 풀었습니다..
- 방법 1: 이분탐색 -> 종유석과 석순을 따로 저장 후, 각각의 높이에 대해서 몇개가 부딪히는지를 이분탐색으로 찾습니다.
- 방법 2: 누적합 -> 높이가 2인 종유석이 부딪힌다면, 높이가 3, 4, 5...인 종유석도 모두 부딪히는 것을 이용해서 구합니다.
없습니다

solved 개똥벌레 - 240ms 119240kb

---

Baekjoon/벽 부수고 이동하기/벽 부수고 이동하기_이정명.java

- #190 
- 어렵지는 않았으나, 머릿속에서 혼란이 좀 있었던 문제였습니다. 벽을 부수지 않았을 때와 1번 부쉈을 떄를 별도의 상태로 관리했습니다.
- 3차원 배열
- 그래프 탐색 (BFS)
- 벽을 부술 수 있는 횟수가 늘어난다면 어떻게 진행하는 것이 최선일지 아이디어가 잘 안떠오릅니다. (그냥 배열의 길이 늘리기?)

solved 벽 부수고 이동하기 - 520ms 109056kb

---

Baekjoon/최소비용 구하기/최소비용 구하기_이정명.java

- #205 
- 쉬웠습니다. 기본적인 다익스트라 문제였습니다.
- 다익스트라
- 없습니다.
-

solved 최소비용 구하기 - 404ms 45944kb

---

Baekjoon/사이클 게임/사이클 게임_박수빈.java

- #204
- 유니온파인드를 복기하기 좋았다
- 유니온파인드
- 딱히 없다

solved 사이클 게임 - 648ms 125536kb

---

Baekjoon/가운데를 말해요/가운데를 말해요_김예지.py

- #202 
어려웠습니다. 
우선순위 큐를 이용하는건 알겠는데,,, 처음엔 그냥 heapq를 쓰려했지만 
이 구조는 완전이진트리 구조로 이루어져서 부모노드 < 자식노드는 맞지만 자식노드 사이의 크기 비교는 하지 않기때문에 두개의 heapq를 이용했습니다. (heappop으로는 항상 최솟값을 꺼내주기 때문에)
수를 절반으로 나눠서 큰수들의 힙, 작은 수들의 힙으로 관리했습니다.
max_heap의 가장 작은 값 == 중간값임을 이용해서 
중간값보다 크면 큰수들의 힙으로 넣어주고, 작으면 작은 수들의 힙으로 넣어주는 등의 업데이트를 통해 중간값을 관리했습니다.
다른 방법이 있을까요? 파이썬의 경우 heapq으로 우선순위 큐를 사용하는데, 다른 언어는 직접 구현하시나요?

solved 가운데를 말해요 - 220ms 39016kb

---

Baekjoon/가운데를 말해요/가운데를 말해요_이정명.java

#202 
- 양쪽 PQ를 쓰는데 어떻게 관리할지를 생각하는 부분 제외하고는 괜찮았습니다.
- PQ를 양쪽으로 두고, 길이를 기준으로 서로 조절을 잘 해주면 풀 수 있는 문제였습니다.
- Priority Queue
- 다른 방법으로 푸신 분이 있는지 궁금합니다.

solved 최소비용 구하기 - 372ms 40580kb

---

Baekjoon/나무 재테크/나무 재테크_박세건.java

- #217 
- 구현 연습하기 좋은 문제
- 반복되는 사계절을 모듈화해서 해결
- 없습니다.

solved 나무 재테크 - 1160ms 296200kb

---

Baekjoon/상어 초등학교/상어 초등학교_박세건.java

- #220 
- 구현 방식에 대해 설계하는 시간을 가졌다면 더 빨리 풀 수 있었을거라 생각했음
- 같이 앉고 싶은 친구들에 대한 정보를 Set으로 관리해서 해결
- 없습니다.

solved 상어 초등학교 - 244ms 25488kb

---

Programmers/수식 복원하기/수식 복원하기_김예지.py

- #218 
n진법 출력이 헷갈려서 좀 걸렸습니다..
그냥 구현.....
너무 더럽게 푼 것 같아서 정리가 필요할 것 같습니다
없습니다

solved 수식 복원하기 - 0.54ms 9.5mb

---

Baekjoon/상어 초등학교/상어 초등학교_김예지.py

- #220 
처음에 냅다 풀었더니 오래걸리고 조건을 중간중간 놓쳐서 오래걸렸습니다..
우선 순위가 여러개 -> 비어있는 칸마다 우선순위를 저장하고 정렬 후에 배치
없습니다

solved 상어 초등학교 - 272ms 32412kb
